spring:
  datasource:
    url: jdbc:mysql://<AWS-RDS-ENDPOINT>:3306/stoq_db
    username: rds_user
    password: rds_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
