spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:15295/railway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: EyZJwlKTUQeEQmBTXLmjYosNZmTCdhrt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong
