spring:
  datasource:
    url: jdbc:mysql://gondola.proxy.rlwy.net:58630/railway
    username: root
    password: bAOZUBygmTsxwqIDlMCEeCwjTfiQTXHm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong
