spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:15295/railway
    username: root
    password: EyZJwlKTUQeEQmBTXLmjYosNZmTCdhrt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong


iamport:
  api-key: 0233760512381147
  api-secret: npvnKFv4D4qTtjjKTduHtYD8VsiRPL7142hYhPgZ56imn9n0PHoFdZ3beckiWRO4NirwCsJxeEJRuLD9

kakao:
  rest-api-key: 07976b4d3ac9d7da5578981736b452f5