spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:15295/railway
    username: root
    password: EyZJwlKTUQeEQmBTXLmjYosNZmTCdhrt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong
