jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stoq_db
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
