spring:
  datasource:
    url: jdbc:mysql://shortline.proxy.rlwy.net.48048/railway
    username: root
    password: DKAXLnBPoleoQoTFdJKABfHfZwQQkLCV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mystudyroomcafeSTOQsecretkeyissoooooooooooooooooooooolong
